### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by XeNoXXX54** [layou233/ZBChecker#1]
Im opening the .bat its showing a cmd prompt and leaving nothing else.

**Comment by XeNoXXX54** [comment]
Just it open and its closing right after

https://user-images.githubusercontent.com/75134564/111065619-f094d000-84ba-11eb-986f-4cfa700392b4.mp4

**Comment by layou233** [comment]
According to the content of the video, you downloaded the source code of the project, not the compiled program.  
Developers use the gradlew.bat To compile and debug the program automatically, but I know all you need is to try the program.  
So go back to the main page of the repository and go to the release tab to download the built file.
