### ISSUE TITLE
Proxies

### ISSUE THREAD

**Issue by EduardsVijups** [layou233/ZBChecker#2]
Is there a way i can add my own proxies and if so does it use http or socks?

**Comment by EduardsVijups** [comment]
I managed to figure out how to use the proxies, but some errors did show up i think i can fix.

Edit 1: Spelling

Edit 2: I forgot to put .txt at the end of my combos file but it still thinks i use cloud mode. weird.

**Comment by EduardsVijups** [comment]
It always wants to use cloud mode and if you respond explain what to fill in here if you even have to.
![Ekrānattēls no 2021-04-04 14-00-37](https://user-images.githubusercontent.com/48444373/113506565-46a2e380-954e-11eb-82b1-00f2270053b1.png)

**Comment by layou233** [comment]
Have you turned the `useProxyApi` to false?  
Proxyfile only be used when `useProxyApi` is turned off. It should be no bugs there becuz I have tried this function for several times...?  
In addition, do you mean `Cloud Mode` or `ProxyAPI` by `cloud mode` that you told?

**Comment by layou233** [comment]
For socks bugs, in fact, I know what causes the bug.  
https://github.com/layou233/ZBChecker/blob/4f976d1a5e881a5bf202f0eb565603ab88d03e9b/src/main/java/lau/ZBChecker/threads/CheckThread.java#L87  
This method is only support for HTTP proxies, but not support SOCKS.  
It seems that there are few libraries that have function for http requests that can easily work with SOCKS. This means that I need to rewrite the socket from the underlying code to implement the proxy. Unless I can find another library that can be easily implemented.  
Of course, this job may not be difficult, and many similar solutions can be found on the Internet, but in fact I don’t have more free time. If you are interested in helping me solve this problem, I would be very grateful.

**Comment by EduardsVijups** [comment]
I tried version 0.1 and it somehow worked. Btw i was using http proxies, useProxyApi was set to false and there were a lot of errors
![Ekrānattēls no 2021-04-06 11-58-39](https://user-images.githubusercontent.com/48444373/113686122-98bf4280-96cf-11eb-9676-ace34e651f64.png)
![Ekrānattēls no 2021-04-06 11-58-57](https://user-images.githubusercontent.com/48444373/113686133-9c52c980-96cf-11eb-9db2-717ad46e2664.png)

**Comment by EduardsVijups** [comment]
DO NOT DECOMPILE THE FILE IT WILL BREAK. yeaaaaaa i installed it again and it worked. :)

**Comment by EduardsVijups** [comment]
when i decompiled version 0.1 it also broke so i guess dont do that for 0.1 also.
